version: "3"

x-vars:
  - &ROOT_PATH /api/shobo-kofu

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    env_file:
      - .env
    environment:
      PYTHON_ENV: ${PYTHON_ENV:-development}
      ROOT_PATH: *ROOT_PATH
      PYTHONPATH: /
      APP_MODULE: app.main:app
    volumes:
      - ./app:/app
    ports:
      - ${PORT:-8000}:80

  db:
    image: postgres:latest
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
